### ISSUE TITLE
Operator `into` has been deprecated -- it's not available in DSL2 syntax

### ISSUE THREAD

**Issue by jaktherenegade** [scilus/disconets_flow#2]
Good morning, 
I try to use your script with my data but I got an error in the script main.nf, line 72 with the following error: 
Operator `into` has been deprecated -- it's not available in DSL2 syntax
I use UBUNTU 18.2 with NextFlow 22.04.5

I send you here the nextflow log
[nextflow.log](https://github.com/scilus/disconets_flow/files/9575394/nextflow.log)

Can you correct your code or explain me how to execute it. 

Thank you very much for your work.

**Comment by arnaudbore** [comment]
Hi @jaktherenegade,
Please give it a try with nextflow 21.* It should work.

**Comment by jaktherenegade** [comment]
Indeed, it works with the version Nextflow 21.10.0
